### PR TITLE
Fall schedule

### PR DESCRIPTION
**Pull request by SleekPanther**
Updated schedule for fall until December
**Added Reservation instructions to library page**
Mission page cleanup

### CODE REVIEW

**Comment by SleekPanther** [comment]
Updated schedule for fall until December
**Added Reservation instructions to library page**
Mission page cleanup

**Comment by Blquinn** [comment]
This still needs to get merged right? @SleekPanther

**Comment by SleekPanther** [comment]
@Blquinn Yeah, changed a few things last week. It's mostly cleanup and some clarifications for how people should use our system, and some info where people should bring books during the fall
But I noticed the pull request has conflicts

**Comment by Blquinn** [comment]
Yeah don't worry about it. 

Also, you don't have to commit so much. Only commit when you're done a significant mount of work, ie done making html changes or something like that. Otherwise it's hard to look back through old commits. 
Just save normally, then when your done use 
git add -A
git commit -m 
then push

**Comment by Blquinn** [comment]
You can also squash commits after if you prefer.

**Pull request closed without merging**
